# Generated by Django 4.2.11 on 2026-01-29 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("basic", "0004_citydatabase_pin_code_companydatabase_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volume", models.DecimalField(decimal_places=2, max_digits=10)),
                ("short_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "re_order_level",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "re_order_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("has_expiry", models.BooleanField(default=False)),
                ("shelf_life", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "qr_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("movement", models.JSONField(blank=True, default=list, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materials",
                "db_table": "material",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Material Category",
                "verbose_name_plural": "Material Categories",
                "db_table": "material_category",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movement_name", models.CharField(max_length=100, unique=True)),
                (
                    "movement_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("source_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "destination_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "material_movement",
                "ordering": ["sort_order", "movement_name"],
                "unique_together": {("movement_name", "movement_code")},
            },
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plant_name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_operational", models.BooleanField(default=True)),
                ("address_line1", models.TextField(blank=True, null=True)),
                ("address_line2", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basic.citydatabase",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basic.companydatabase",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basic.countrydatabase",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basic.currencydatabase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant",
                "verbose_name_plural": "Plants",
                "db_table": "plant",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=50, null=True)),
                ("is_manufacturing", models.BooleanField(default=False)),
                ("is_distribution", models.BooleanField(default=False)),
                ("is_service", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "plant_type",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("is_raw_material", models.BooleanField(default=False)),
                ("is_finished_goods", models.BooleanField(default=False)),
                ("is_spare_parts", models.BooleanField(default=False)),
                ("is_transit", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "warehouse_type",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("warehouse_name", models.CharField(max_length=150)),
                (
                    "warehouse_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("short_name", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("address_line1", models.TextField(blank=True, null=True)),
                ("address_line2", models.TextField(blank=True, null=True)),
                (
                    "max_capacity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basic.citydatabase",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basic.countrydatabase",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouses",
                        to="ims.plant",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basic.statedatabase",
                    ),
                ),
                (
                    "warehouse_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ims.warehousetype",
                    ),
                ),
            ],
            options={
                "db_table": "warehouse",
                "ordering": ["warehouse_name"],
            },
        ),
        migrations.CreateModel(
            name="Units",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("base_quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("short_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Units",
                "verbose_name_plural": "Units",
                "db_table": "units",
                "ordering": ["-created_at"],
                "unique_together": {("name", "code", "short_name")},
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("is_base_unit", models.BooleanField(default=False)),
                ("short_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ims.units",
                    ),
                ),
            ],
            options={
                "verbose_name": "UOM",
                "verbose_name_plural": "UOMs",
                "db_table": "uom",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_name", models.CharField(max_length=100, unique=True)),
                (
                    "status_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "transaction_status",
                "ordering": ["sort_order", "status_name"],
                "unique_together": {("status_name", "status_code")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transaction_name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("source_code", models.CharField(max_length=20)),
                ("destination_code", models.CharField(max_length=20)),
                ("volume", models.DecimalField(decimal_places=3, max_digits=14)),
                ("is_shipped", models.BooleanField(default=False)),
                ("history", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ims.material"
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ims.materialmovement",
                    ),
                ),
                (
                    "transaction_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ims.transactionstatus",
                    ),
                ),
                (
                    "units_of_measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ims.unitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
            },
        ),
        migrations.CreateModel(
            name="StorageLocationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("is_open", models.BooleanField(default=False)),
                ("is_rack", models.BooleanField(default=False)),
                ("is_cold_storage", models.BooleanField(default=False)),
                ("is_hazardous", models.BooleanField(default=False)),
                ("is_quarantine", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "storage_location_type",
                "ordering": ["sort_order", "name"],
                "unique_together": {("name", "code")},
            },
        ),
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=150)),
                ("location_code", models.CharField(max_length=50)),
                ("short_name", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_capacity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                ("is_pickable", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "storage_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ims.storagelocationtype",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="storage_locations",
                        to="ims.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "storage_location",
                "ordering": ["location_name"],
            },
        ),
        migrations.AddField(
            model_name="plant",
            name="plant_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ims.planttype",
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basic.statedatabase",
            ),
        ),
        migrations.CreateModel(
            name="MaterialType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ims.materialcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Type",
                "verbose_name_plural": "Material Types",
                "db_table": "material_type",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_code", models.CharField(max_length=10)),
                ("volume", models.DecimalField(decimal_places=3, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ims.material"
                    ),
                ),
                (
                    "related_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ims.transaction",
                    ),
                ),
                (
                    "units_of_measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ims.unitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "material_report",
            },
        ),
        migrations.CreateModel(
            name="MaterialGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Material Group",
                "verbose_name_plural": "Material Groups",
                "db_table": "material_group",
                "ordering": ["-created_at"],
                "unique_together": {("name", "code", "short_name")},
            },
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="material_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ims.materialgroup",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="base_uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials",
                to="ims.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="issue_uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue_materials",
                to="ims.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="material_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ims.materialtype",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="purchase_uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_materials",
                to="ims.unitofmeasure",
            ),
        ),
    ]
