# Generated by Django 4.2.11 on 2026-01-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ims", "0001_initial"),
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials",
                to="vendor.vendor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="warehouse",
            unique_together={("warehouse_name", "warehouse_code", "short_name")},
        ),
        migrations.AlterUniqueTogether(
            name="unitofmeasure",
            unique_together={("name", "code", "short_name")},
        ),
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={("transaction_name",)},
        ),
        migrations.AlterUniqueTogether(
            name="storagelocation",
            unique_together={("location_name", "location_code", "short_name")},
        ),
        migrations.AlterUniqueTogether(
            name="plant",
            unique_together={("plant_name", "code", "short_name")},
        ),
        migrations.AlterUniqueTogether(
            name="materialtype",
            unique_together={("name", "code", "short_name")},
        ),
        migrations.AlterUniqueTogether(
            name="materialreport",
            unique_together={("material", "location_code", "units_of_measure")},
        ),
        migrations.AlterUniqueTogether(
            name="materialcategory",
            unique_together={("name", "code", "short_name")},
        ),
        migrations.AlterUniqueTogether(
            name="material",
            unique_together={("material_name", "code", "short_name")},
        ),
    ]
