# Generated by Django 4.2.11 on 2026-01-30 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0005_businessarea_company_businessarea_creator_and_more"),
        ("ims", "0003_material_company_material_creator_material_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basic.companydatabase",
            ),
        ),
    ]
