# Generated by Django 4.2.11 on 2026-02-17 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ims", "0005_po_status_purchaseorder_purchaseorderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="viewer",
            field=models.ManyToManyField(
                blank=True,
                related_name="viewer_transaction",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
