# Generated by Django 4.2.11 on 2026-02-17 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ims", "0006_transaction_viewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="viewer",
            field=models.ManyToManyField(
                blank=True,
                related_name="viewer_purchase_order",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
