# Generated by Django 4.2.11 on 2026-02-18 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ims", "0007_purchaseorder_viewer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialmovement",
            name="destination_code",
        ),
        migrations.RemoveField(
            model_name="materialmovement",
            name="source_code",
        ),
    ]
