# Generated by Django 4.2.11 on 2026-02-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ims", "0008_remove_materialmovement_destination_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialmovement",
            name="from_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="materialmovement",
            name="to_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
