# Generated by Django 4.2.11 on 2026-02-18 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ims", "0009_materialmovement_from_name_materialmovement_to_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="materialmovement",
            old_name="from_name",
            new_name="destination",
        ),
        migrations.RenameField(
            model_name="materialmovement",
            old_name="to_name",
            new_name="source",
        ),
    ]
