# Generated by Django 4.2.11 on 2026-02-18 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0007_alter_userdatabase_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ims", "0010_rename_from_name_materialmovement_destination_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_base_uom",
                        to="ims.unitofmeasure",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stocks",
                        to="basic.companydatabase",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_stocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_updates",
                        to="ims.transaction",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocks",
                        to="ims.material",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocks",
                        to="ims.storagelocation",
                    ),
                ),
            ],
            options={
                "db_table": "stock",
                "indexes": [
                    models.Index(fields=["material"], name="stock_materia_317ffb_idx"),
                    models.Index(
                        fields=["storage_location"], name="stock_storage_c99b59_idx"
                    ),
                ],
                "unique_together": {("material", "storage_location", "batch_number")},
            },
        ),
    ]
