# Generated by Django 4.2.11 on 2026-02-18 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ims", "0011_stock"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("material", "storage_location")},
        ),
    ]
