# Generated by Django 4.2.11 on 2026-02-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ims", "0012_alter_stock_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="is_released",
            field=models.BooleanField(default=False),
        ),
    ]
