# Generated by Django 4.2.11 on 2026-02-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ims", "0013_purchaseorder_is_released"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="warehouse",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="storage_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="ims.storagelocation",
            ),
        ),
    ]
