# Generated by Django 4.2.11 on 2026-02-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ims", "0015_baginventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="baginventory",
            name="is_collected",
            field=models.BooleanField(default=False),
        ),
    ]
