# Generated by Django 4.2.11 on 2026-02-23 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0007_alter_userdatabase_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ims", "0016_baginventory_is_collected"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumeAndScrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("is_scrap", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_consume_and_scraps",
                        to="basic.companydatabase",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_consume_and_scraps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consume_and_scraps",
                        to="ims.material",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consume_and_scraps",
                        to="ims.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "consume_and_scrap",
                "ordering": ["-created_at"],
                "unique_together": {("transaction", "material")},
            },
        ),
    ]
