# Generated by Django 4.2.11 on 2026-01-27 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessGroupDatabase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("access_group_name", models.CharField(max_length=100, unique=True)),
                ("access_group_code", models.CharField(max_length=100, unique=True)),
                ("access_group_description", models.CharField(max_length=100)),
                ("url", models.CharField(blank=True, max_length=100, null=True)),
                ("can_create", models.BooleanField(default=False)),
                ("can_read", models.BooleanField(default=False)),
                ("can_update", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Access Group",
                "verbose_name_plural": "Access Groups",
                "db_table": "access_group_database",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccessGroupUserDatabase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Access Group User",
                "verbose_name_plural": "Access Group Users",
                "db_table": "access_group_user_database",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalProcess",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("data", models.BinaryField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Approval Process",
                "verbose_name_plural": "Approval Processes",
                "db_table": "approval_process",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStack",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Approval Stack",
                "verbose_name_plural": "Approval Stacks",
                "db_table": "approval_stack",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStatusDatabase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Approval Status",
                "verbose_name_plural": "Approval Statuses",
                "db_table": "approval_status_database",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelNameDatabase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=100, unique=True)),
                ("model_code", models.CharField(max_length=100, unique=True)),
                ("model_app", models.CharField(max_length=100)),
                ("model_description", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserModelPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_create", models.BooleanField(null=True)),
                ("can_read", models.BooleanField(null=True)),
                ("can_update", models.BooleanField(null=True)),
                ("can_delete", models.BooleanField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ams.modelnamedatabase",
                    ),
                ),
            ],
            options={
                "db_table": "user_model_permission",
                "ordering": ["-created_at"],
            },
        ),
    ]
