# Generated by Django 4.2.11 on 2026-01-27 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("basic", "0001_initial"),
        ("ams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodelpermission",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalstack",
            name="next_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ams.approvalstack",
            ),
        ),
        migrations.AddField(
            model_name="approvalstack",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalprocess",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basic.companydatabase",
            ),
        ),
        migrations.AddField(
            model_name="approvalprocess",
            name="model_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ams.modelnamedatabase",
            ),
        ),
        migrations.AddField(
            model_name="approvalprocess",
            name="recent_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ams.approvalstack",
            ),
        ),
        migrations.AddField(
            model_name="approvalprocess",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ams.approvalstatusdatabase",
            ),
        ),
        migrations.AddField(
            model_name="accessgroupuserdatabase",
            name="access_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ams.accessgroupdatabase",
            ),
        ),
        migrations.AddField(
            model_name="accessgroupuserdatabase",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accessgroupdatabase",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basic.companydatabase",
            ),
        ),
        migrations.AddField(
            model_name="accessgroupdatabase",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ams.modelnamedatabase",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usermodelpermission",
            unique_together={("user", "model")},
        ),
        migrations.AlterUniqueTogether(
            name="accessgroupuserdatabase",
            unique_together={("access_group", "user")},
        ),
    ]
