# Generated by Django 4.2.11 on 2026-01-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalstack",
            name="is_first",
            field=models.BooleanField(default=False),
        ),
    ]
