# Generated by Django 4.2.11 on 2026-01-28 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0003_approvalstack_is_first"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("create", models.BooleanField(default=False)),
                ("delete", models.BooleanField(default=False)),
                ("update", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ams.modelnamedatabase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Model",
                "verbose_name_plural": "Subscription Models",
                "db_table": "subscription_model",
                "ordering": ["-created_at"],
                "unique_together": {("model",)},
            },
        ),
    ]
