# Generated by Django 4.2.11 on 2026-01-28 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0002_tempmodel"),
        ("ams", "0004_subscriptionmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionmodel",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="subscriptionmodel",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basic.companydatabase",
            ),
        ),
    ]
