# Generated by Django 4.2.11 on 2026-01-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0005_subscriptionmodel_code_subscriptionmodel_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalprocess",
            name="method",
            field=models.TextField(default="POST"),
        ),
    ]
