# Generated by Django 4.2.11 on 2026-01-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0006_approvalprocess_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalprocess",
            name="update_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
