# Generated by Django 4.2.11 on 2026-01-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0007_approvalprocess_update_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionmodel",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
