# Generated by Django 4.2.11 on 2026-01-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0008_alter_subscriptionmodel_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalprocess",
            name="code",
            field=models.CharField(max_length=100),
        ),
    ]
