# Generated by Django 4.2.11 on 2026-01-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0009_alter_approvalprocess_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalstack",
            name="comments",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
