# Generated by Django 4.2.11 on 2026-01-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0010_approvalstack_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalprocess",
            name="comments",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
