# Generated by Django 4.2.11 on 2026-01-29 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0011_approvalprocess_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptionmodel",
            old_name="delete",
            new_name="can_delete",
        ),
    ]
