# Generated by Django 4.2.11 on 2026-01-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0013_accessgroupdatabase_creator_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvalprocess",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Shadow_model",
                "verbose_name_plural": "Shadow_model",
            },
        ),
        migrations.AlterModelOptions(
            name="approvalstack",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Linked_List_Approver",
                "verbose_name_plural": "Linked_List_Approver",
            },
        ),
        migrations.AlterModelOptions(
            name="approvalstatusdatabase",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "StatusApproval",
                "verbose_name_plural": "StatusApproval",
            },
        ),
        migrations.AlterModelOptions(
            name="subscriptionmodel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
        migrations.AddField(
            model_name="accessgroupuserdatabase",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usermodelpermission",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
