# Generated by Django 4.2.11 on 2026-01-31 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0005_businessarea_company_businessarea_creator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ams", "0014_alter_approvalprocess_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RowLevelPermission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basic.companydatabase",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ams.accessgroupdatabase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Row Level Permission",
                "verbose_name_plural": "Row Level Permissions",
                "db_table": "row_level_permission",
                "ordering": ["-created_at"],
                "unique_together": {("group", "code")},
            },
        ),
    ]
