# Generated by Django 4.2.11 on 2026-01-31 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ams", "0015_rowlevelpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="rowlevelpermission",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_row_permission",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
