# Generated by Django 4.2.11 on 2026-02-09 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ams", "0016_rowlevelpermission_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accessgroupuserdatabase",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="accessgroupdatabase",
            name="model",
        ),
        migrations.AddField(
            model_name="accessgroupuserdatabase",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ams.modelnamedatabase",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accessgroupuserdatabase",
            unique_together={("access_group", "user", "model")},
        ),
    ]
