# Generated by Django 4.2.11 on 2026-02-09 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0005_businessarea_company_businessarea_creator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ams", "0017_alter_accessgroupuserdatabase_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalprocess",
            name="sub_task_uuid",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="approvalprocess",
            unique_together={("model_name", "code", "method", "update_id")},
        ),
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField(blank=True, null=True)),
                ("sub_task_uuid", models.UUIDField(blank=True, null=True)),
                ("method", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_sub_task",
                        to="basic.companydatabase",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_sub_task",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ams.modelnamedatabase",
                    ),
                ),
            ],
            options={
                "verbose_name": "SubTask",
                "verbose_name_plural": "SubTask",
                "db_table": "sub_task",
                "ordering": ["-created_at"],
            },
        ),
    ]
