# Generated by Django 4.2.11 on 2026-02-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0018_approvalprocess_sub_task_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="instance_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
