# Generated by Django 4.2.11 on 2026-02-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0019_subtask_instance_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="is_executed",
            field=models.BooleanField(default=False),
        ),
    ]
