# Generated by Django 4.2.11 on 2026-02-10 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0021_alter_approvalprocess_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="approvalprocess",
            unique_together={("model_name", "code", "method", "update_id", "id")},
        ),
    ]
