# Generated by Django 4.2.11 on 2026-02-11 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0007_alter_userdatabase_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ams", "0022_alter_approvalprocess_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationBox",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_navigation_box",
                        to="basic.companydatabase",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_navigation_box",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Box",
                "verbose_name_plural": "Navigation Boxes",
                "db_table": "navigation_box",
                "ordering": ["-created_at"],
            },
        ),
    ]
