# Generated by Django 4.2.11 on 2026-02-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0023_navigationbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalprocess",
            name="bloc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
