# Generated by Django 4.2.11 on 2026-01-27 08:29

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0014_remove_user_is_new_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_photo",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="employee_photos/",
                    ),
                ),
                ("user_code", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "user_database",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CityDatabase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("city_name", models.CharField(max_length=100, unique=True)),
                ("city_code", models.CharField(max_length=100, unique=True)),
                (
                    "city_logo",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="city_logos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "db_table": "city_database",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CountryDatabase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("country_name", models.CharField(max_length=100, unique=True)),
                ("country_code", models.CharField(max_length=100, unique=True)),
                ("country_mobile", models.CharField(max_length=100)),
                (
                    "country_logo",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="country_logos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "country_database",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LanguageDatabase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("language_name", models.CharField(max_length=100, unique=True)),
                ("language_code", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "db_table": "language_database",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusDatabase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=100)),
                ("status_code", models.CharField(max_length=100, unique=True)),
                ("status_description", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Statuses",
                "db_table": "status_database",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusDatabaseUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=100)),
                ("status_code", models.CharField(max_length=100, unique=True)),
                ("status_description", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Statuses",
                "db_table": "status_database_user",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserTypeDatabase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=100)),
                ("type_code", models.CharField(max_length=100, unique=True)),
                ("type_description", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Type",
                "verbose_name_plural": "User Types",
                "db_table": "user_type_database",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StateDatabase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("state_name", models.CharField(max_length=100, unique=True)),
                ("state_code", models.CharField(max_length=100, unique=True)),
                (
                    "state_logo",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="state_logos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basic.countrydatabase",
                    ),
                ),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
                "db_table": "state_database",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyDatabase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "organization_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("company_name", models.CharField(max_length=100, unique=True)),
                ("company_code", models.CharField(max_length=100, unique=True)),
                (
                    "company_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="company_logos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basic.citydatabase",
                    ),
                ),
                (
                    "company_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basic.countrydatabase",
                    ),
                ),
                (
                    "parent_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basic.companydatabase",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basic.statedatabase",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="basic.statusdatabase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "db_table": "company_database",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="citydatabase",
            name="city_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basic.statedatabase",
            ),
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basic.statusdatabaseuser",
            ),
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="user_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basic.companydatabase",
            ),
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="user_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basic.usertypedatabase",
            ),
        ),
    ]
