# Generated by Django 4.2.11 on 2026-01-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="temp/"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="temp/"
                    ),
                ),
                ("test", models.CharField(max_length=100)),
                ("boolean", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Temp",
                "verbose_name_plural": "Temps",
                "db_table": "temp_model",
                "ordering": ["-created_at"],
            },
        ),
    ]
