# Generated by Django 4.2.11 on 2026-01-29 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0002_tempmodel"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userdatabase",
            unique_together={("username", "email")},
        ),
    ]
