# Generated by Django 4.2.11 on 2026-01-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0003_alter_userdatabase_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="citydatabase",
            name="pin_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companydatabase",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basic.languagedatabase",
            ),
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="device_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="relationship_emergency_contact",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companydatabase",
            name="organization_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="companydatabase",
            unique_together={
                ("company_name", "company_code", "organization_id", "parent_company")
            },
        ),
        migrations.AlterUniqueTogether(
            name="usertypedatabase",
            unique_together={("type", "type_code")},
        ),
        migrations.CreateModel(
            name="PositionDatabase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("position", models.CharField(max_length=100)),
                ("position_code", models.CharField(max_length=100, unique=True)),
                ("position_description", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "db_table": "position_database",
                "ordering": ["-created_at"],
                "unique_together": {("position", "position_code")},
            },
        ),
        migrations.CreateModel(
            name="CurrencyDatabase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("currency_name", models.CharField(max_length=100, unique=True)),
                ("currency_code", models.CharField(max_length=100, unique=True)),
                ("currency_symbol", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "db_table": "currency_database",
                "ordering": ["-created_at"],
                "unique_together": {("currency_name", "currency_code")},
            },
        ),
        migrations.CreateModel(
            name="BusinessSector",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("business_sector", models.CharField(max_length=100)),
                ("business_sector_code", models.CharField(max_length=100, unique=True)),
                ("business_sector_description", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business Sector",
                "verbose_name_plural": "Business Sectors",
                "db_table": "business_sector",
                "ordering": ["-created_at"],
                "unique_together": {("business_sector", "business_sector_code")},
            },
        ),
        migrations.CreateModel(
            name="BusinessArea",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("business_area", models.CharField(max_length=100)),
                ("business_area_code", models.CharField(max_length=100, unique=True)),
                ("business_area_description", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business Area",
                "verbose_name_plural": "Business Areas",
                "db_table": "business_area",
                "ordering": ["-created_at"],
                "unique_together": {("business_area", "business_area_code")},
            },
        ),
        migrations.AddField(
            model_name="companydatabase",
            name="business_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basic.businessarea",
            ),
        ),
        migrations.AddField(
            model_name="companydatabase",
            name="business_sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basic.businesssector",
            ),
        ),
        migrations.AddField(
            model_name="companydatabase",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basic.currencydatabase",
            ),
        ),
        migrations.AddField(
            model_name="userdatabase",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="basic.positiondatabase",
            ),
        ),
    ]
