# Generated by Django 4.2.11 on 2026-02-10 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0005_businessarea_company_businessarea_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdatabase",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
